"""autogenerated by genpy from croc_gs/windParameters.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class windParameters(genpy.Message):
  _md5sum = "ed4849b220add50d51f893f97b23598e"
  _type = "croc_gs/windParameters"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header


geometry_msgs/Vector3 baseVector
float32 minAlpha
float32 maxAlpha
float32 minBeta
float32 maxBeta
float32 minGamma
float32 maxGamma
float32 minKappa
float32 maxKappa

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','baseVector','minAlpha','maxAlpha','minBeta','maxBeta','minGamma','maxGamma','minKappa','maxKappa']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,baseVector,minAlpha,maxAlpha,minBeta,maxBeta,minGamma,maxGamma,minKappa,maxKappa

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(windParameters, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.baseVector is None:
        self.baseVector = geometry_msgs.msg.Vector3()
      if self.minAlpha is None:
        self.minAlpha = 0.
      if self.maxAlpha is None:
        self.maxAlpha = 0.
      if self.minBeta is None:
        self.minBeta = 0.
      if self.maxBeta is None:
        self.maxBeta = 0.
      if self.minGamma is None:
        self.minGamma = 0.
      if self.maxGamma is None:
        self.maxGamma = 0.
      if self.minKappa is None:
        self.minKappa = 0.
      if self.maxKappa is None:
        self.maxKappa = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.baseVector = geometry_msgs.msg.Vector3()
      self.minAlpha = 0.
      self.maxAlpha = 0.
      self.minBeta = 0.
      self.maxBeta = 0.
      self.minGamma = 0.
      self.maxGamma = 0.
      self.minKappa = 0.
      self.maxKappa = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d8f.pack(_x.baseVector.x, _x.baseVector.y, _x.baseVector.z, _x.minAlpha, _x.maxAlpha, _x.minBeta, _x.maxBeta, _x.minGamma, _x.maxGamma, _x.minKappa, _x.maxKappa))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.baseVector is None:
        self.baseVector = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.baseVector.x, _x.baseVector.y, _x.baseVector.z, _x.minAlpha, _x.maxAlpha, _x.minBeta, _x.maxBeta, _x.minGamma, _x.maxGamma, _x.minKappa, _x.maxKappa,) = _struct_3d8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d8f.pack(_x.baseVector.x, _x.baseVector.y, _x.baseVector.z, _x.minAlpha, _x.maxAlpha, _x.minBeta, _x.maxBeta, _x.minGamma, _x.maxGamma, _x.minKappa, _x.maxKappa))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.baseVector is None:
        self.baseVector = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.baseVector.x, _x.baseVector.y, _x.baseVector.z, _x.minAlpha, _x.maxAlpha, _x.minBeta, _x.maxBeta, _x.minGamma, _x.maxGamma, _x.minKappa, _x.maxKappa,) = _struct_3d8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3d8f = struct.Struct("<3d8f")
