"""autogenerated by genpy from croc_command/PID.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PID(genpy.Message):
  _md5sum = "b20cdc5d72609b58c4b9377ff7eb77dd"
  _type = "croc_command/PID"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float32 p_gain
float32 i_gain
float32 d_gain
float32 i_max
float32 i_min


float32 p_error
float32 i_error
float32 d_error

float32 goal

float32 hover

float32 pid_value

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','p_gain','i_gain','d_gain','i_max','i_min','p_error','i_error','d_error','goal','hover','pid_value']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,p_gain,i_gain,d_gain,i_max,i_min,p_error,i_error,d_error,goal,hover,pid_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PID, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.p_gain is None:
        self.p_gain = 0.
      if self.i_gain is None:
        self.i_gain = 0.
      if self.d_gain is None:
        self.d_gain = 0.
      if self.i_max is None:
        self.i_max = 0.
      if self.i_min is None:
        self.i_min = 0.
      if self.p_error is None:
        self.p_error = 0.
      if self.i_error is None:
        self.i_error = 0.
      if self.d_error is None:
        self.d_error = 0.
      if self.goal is None:
        self.goal = 0.
      if self.hover is None:
        self.hover = 0.
      if self.pid_value is None:
        self.pid_value = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.p_gain = 0.
      self.i_gain = 0.
      self.d_gain = 0.
      self.i_max = 0.
      self.i_min = 0.
      self.p_error = 0.
      self.i_error = 0.
      self.d_error = 0.
      self.goal = 0.
      self.hover = 0.
      self.pid_value = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_11f.pack(_x.p_gain, _x.i_gain, _x.d_gain, _x.i_max, _x.i_min, _x.p_error, _x.i_error, _x.d_error, _x.goal, _x.hover, _x.pid_value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.p_gain, _x.i_gain, _x.d_gain, _x.i_max, _x.i_min, _x.p_error, _x.i_error, _x.d_error, _x.goal, _x.hover, _x.pid_value,) = _struct_11f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_11f.pack(_x.p_gain, _x.i_gain, _x.d_gain, _x.i_max, _x.i_min, _x.p_error, _x.i_error, _x.d_error, _x.goal, _x.hover, _x.pid_value))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.p_gain, _x.i_gain, _x.d_gain, _x.i_max, _x.i_min, _x.p_error, _x.i_error, _x.d_error, _x.goal, _x.hover, _x.pid_value,) = _struct_11f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_11f = struct.Struct("<11f")
