/* Auto-generated by genmsg_cpp for file /home/mike/ros/cyphy_serial_driver/msg/mikoCmd.msg */
#ifndef CYPHY_SERIAL_DRIVER_MESSAGE_MIKOCMD_H
#define CYPHY_SERIAL_DRIVER_MESSAGE_MIKOCMD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace cyphy_serial_driver
{
template <class ContainerAllocator>
struct mikoCmd_ {
  typedef mikoCmd_<ContainerAllocator> Type;

  mikoCmd_()
  : header()
  , pitch(0)
  , roll(0)
  , yaw(0)
  , throttle(0)
  {
  }

  mikoCmd_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pitch(0)
  , roll(0)
  , yaw(0)
  , throttle(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _pitch_type;
  int32_t pitch;

  typedef int32_t _roll_type;
  int32_t roll;

  typedef int32_t _yaw_type;
  int32_t yaw;

  typedef int32_t _throttle_type;
  int32_t throttle;


  typedef boost::shared_ptr< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct mikoCmd
typedef  ::cyphy_serial_driver::mikoCmd_<std::allocator<void> > mikoCmd;

typedef boost::shared_ptr< ::cyphy_serial_driver::mikoCmd> mikoCmdPtr;
typedef boost::shared_ptr< ::cyphy_serial_driver::mikoCmd const> mikoCmdConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cyphy_serial_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "724ec795847189db4c83e17804812733";
  }

  static const char* value(const  ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x724ec795847189dbULL;
  static const uint64_t static_value2 = 0x4c83e17804812733ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cyphy_serial_driver/mikoCmd";
  }

  static const char* value(const  ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This is a message to send command data to an Mikrokopter.\n\
#\n\
# Command data range from -128 to 128 forced by Mikrokopter.\n\
# We couldn't change resolution.\n\
# by Inkyu\n\
\n\
Header header\n\
\n\
int32 pitch\n\
int32 roll\n\
int32 yaw\n\
int32 throttle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pitch);
    stream.next(m.roll);
    stream.next(m.yaw);
    stream.next(m.throttle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct mikoCmd_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cyphy_serial_driver::mikoCmd_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pitch: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<int32_t>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yaw);
    s << indent << "throttle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.throttle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CYPHY_SERIAL_DRIVER_MESSAGE_MIKOCMD_H

