/* Auto-generated by genmsg_cpp for file /home/mike/ros/croc_Pose3D/msg/Pose3D.msg */
#ifndef CROC_POSE3D_MESSAGE_POSE3D_H
#define CROC_POSE3D_MESSAGE_POSE3D_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"
#include "geometry_msgs/Vector3.h"

namespace croc_Pose3D
{
template <class ContainerAllocator>
struct Pose3D_ {
  typedef Pose3D_<ContainerAllocator> Type;

  Pose3D_()
  : header()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , pitch(0.0)
  , roll(0.0)
  , yaw(0.0)
  , linear_acceleration()
  , calculated_linear_velocity()
  {
  }

  Pose3D_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , pitch(0.0)
  , roll(0.0)
  , yaw(0.0)
  , linear_acceleration(_alloc)
  , calculated_linear_velocity(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _pitch_type;
  float pitch;

  typedef float _roll_type;
  float roll;

  typedef float _yaw_type;
  float yaw;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  linear_acceleration;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _calculated_linear_velocity_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  calculated_linear_velocity;


  typedef boost::shared_ptr< ::croc_Pose3D::Pose3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::croc_Pose3D::Pose3D_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Pose3D
typedef  ::croc_Pose3D::Pose3D_<std::allocator<void> > Pose3D;

typedef boost::shared_ptr< ::croc_Pose3D::Pose3D> Pose3DPtr;
typedef boost::shared_ptr< ::croc_Pose3D::Pose3D const> Pose3DConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::croc_Pose3D::Pose3D_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::croc_Pose3D::Pose3D_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace croc_Pose3D

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::croc_Pose3D::Pose3D_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::croc_Pose3D::Pose3D_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::croc_Pose3D::Pose3D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "78a9251aa2bab1e13b97b5f5d91aa653";
  }

  static const char* value(const  ::croc_Pose3D::Pose3D_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x78a9251aa2bab1e1ULL;
  static const uint64_t static_value2 = 0x3b97b5f5d91aa653ULL;
};

template<class ContainerAllocator>
struct DataType< ::croc_Pose3D::Pose3D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "croc_Pose3D/Pose3D";
  }

  static const char* value(const  ::croc_Pose3D::Pose3D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::croc_Pose3D::Pose3D_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
float32 pitch\n\
float32 roll\n\
float32 yaw\n\
\n\
geometry_msgs/Vector3 linear_acceleration\n\
\n\
geometry_msgs/Vector3 calculated_linear_velocity\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::croc_Pose3D::Pose3D_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::croc_Pose3D::Pose3D_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::croc_Pose3D::Pose3D_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::croc_Pose3D::Pose3D_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.pitch);
    stream.next(m.roll);
    stream.next(m.yaw);
    stream.next(m.linear_acceleration);
    stream.next(m.calculated_linear_velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pose3D_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::croc_Pose3D::Pose3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::croc_Pose3D::Pose3D_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "linear_acceleration: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "calculated_linear_velocity: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.calculated_linear_velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CROC_POSE3D_MESSAGE_POSE3D_H

