/* Auto-generated by genmsg_cpp for file /home/mike/ros/croc_command/msg/State.msg */
#ifndef CROC_COMMAND_MESSAGE_STATE_H
#define CROC_COMMAND_MESSAGE_STATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace croc_command
{
template <class ContainerAllocator>
struct State_ {
  typedef State_<ContainerAllocator> Type;

  State_()
  : header()
  , state(0)
  {
  }

  State_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , state(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int16_t _state_type;
  int16_t state;


  typedef boost::shared_ptr< ::croc_command::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::croc_command::State_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct State
typedef  ::croc_command::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::croc_command::State> StatePtr;
typedef boost::shared_ptr< ::croc_command::State const> StateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::croc_command::State_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::croc_command::State_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace croc_command

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::croc_command::State_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::croc_command::State_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::croc_command::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1951e0c38e32ff876c61f0bfad87a62d";
  }

  static const char* value(const  ::croc_command::State_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1951e0c38e32ff87ULL;
  static const uint64_t static_value2 = 0x6c61f0bfad87a62dULL;
};

template<class ContainerAllocator>
struct DataType< ::croc_command::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "croc_command/State";
  }

  static const char* value(const  ::croc_command::State_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::croc_command::State_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
int16 state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::croc_command::State_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::croc_command::State_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::croc_command::State_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::croc_command::State_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct State_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::croc_command::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::croc_command::State_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int16_t>::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CROC_COMMAND_MESSAGE_STATE_H

